name: Build App

on:
  push:
    branches: ['**']

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Install ts-node
        run: yarn add -D ts-node typescript @types/node

      - name: Build application
        run: yarn package
        env:
          NODE_OPTIONS: '--import tsx'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist/
          retention-days: 7
